global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  static_configs:
  - targets:
    - localhost:9090
- job_name: docker
  metrics_path: /metrics
  static_configs:
  - targets:
    - 172.17.0.1:9323
- job_name: node
  metrics_path: /metrics
  static_configs:
  - targets:
    - 172.17.0.1:9100
- job_name: databases
  metrics_path: /metrics
  static_configs:
  - targets:
    - backenddb:9187
    - authcodedb:9187
    - keycloakdb:9187
- job_name: authcode
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets:
    - backendws:8080
- job_name: backend
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets:
    - backendws:8080
- job_name: keycloak
  metrics_path: '/auth/realms/master/metrics'
  static_configs:
  - targets:
    - keycloak:8080
- job_name: frontend
  metrics_path: '/metrics'
  static_configs:
  - targets:
    - frontend:9180
 
